// UnApproved requests


export const unApproveRows = [
  {
    vendorId: 1,
    vendorName: "Snow",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 35,
    status: "Pending",
  },
  {
    vendorId: 2,
    vendorName: "Jamie Lannister",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 42,
    status: "Pending",
  },
  {
    vendorId: 3,
    vendorName: "Lannister",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 45,
    status: "Pending",
  },
  {
    vendorId: 4,
    vendorName: "Stark",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 16,
    status: "Pending",
  },
  {
    vendorId: 5,
    vendorName: "Targaryen",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 22,
    status: "Pending",
  },
  {
    vendorId: 6,
    vendorName: "Melisandre",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 15,
    status: "Pending",
  },
  {
    vendorId: 7,
    vendorName: "Clifford",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 44,
    status: "Pending",
  },
  {
    vendorId: 8,
    vendorName: "Frances",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 36,
    status: "Pending",
  },
  {
    vendorId: 9,
    vendorName: "Roxie",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 65,
    status: "Pending",
  },
  {
    vendorId: 10,
    vendorName: "Roxie",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 65,
    status: "Pending",
  },
];

// Approved requests


//temporary data
export const approveRows = [
  {
    vendorId: 1,
    vendorName: "Snow",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 35,
    status: "Approved",
  },
  {
    vendorId: 2,
    vendorName: "Jamie Lannister",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 42,
    status: "Approved",
  },
  {
    vendorId: 3,
    vendorName: "Lannister",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 45,
    status: "Approved",
  },
  {
    vendorId: 4,
    vendorName: "Stark",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 16,
    status: "Approved",
  },
  {
    vendorId: 5,
    vendorName: "Targaryen",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 22,
    status: "Approved",
  },
  {
    vendorId: 6,
    vendorName: "Melisandre",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 15,
    status: "Approved",
  },
  {
    vendorId: 7,
    vendorName: "Clifford",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 44,
    status: "Approved",
  },
  {
    vendorId: 8,
    vendorName: "Frances",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 36,
    status: "Approved",
  },
  {
    vendorId: 9,
    vendorName: "Roxie",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 65,
    status: "Approved",
  },
  {
    vendorId: 10,
    vendorName: "Roxie",
    SnapShot: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    Numberofdevices: "2",
    creationDate: 65,
    status: "Approved",
  },
];
